### PR TITLE
Apply clang-format to source files

### PR DESCRIPTION
**Pull request by ArthurBandaryk**
Applied clang-format to all source files in this repo, as well as
fixed some lines of code in order to not exceed 80 chars
and replaced __WINDOWS__ macro to _WIN32.

### CODE REVIEW

**Comment by ArthurBandaryk** [comment]
@benh , do you have an idea how can we make [this](https://github.com/3rdparty/stout/blob/7c1968e3d1aa9ace5754a05fc0f84dcad41f4a9d/tests/json_tests.cpp#L291) line of code not to exceed 80 chars?:)

**Comment by ArthurBandaryk** [comment]
Soon I will upload other commits with remaining files which should be formatted with clang-format.

**Comment by benh** [comment]
> @benh , do you have an idea how can we make [this](https://github.com/3rdparty/stout/blob/7c1968e3d1aa9ace5754a05fc0f84dcad41f4a9d/tests/json_tests.cpp#L291) line of code not to exceed 80 chars?:)

No sorry! You'll need to `// clang-format off` and `// clang-format on`.

**Review by benh — APPROVED** [review]

**Comment by ArthurBandaryk** [comment]
@benh , refactoring of the all source files (except submodules) is done!

**Review by benh — APPROVED** [review]

**Pull request merged**
